<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<!-- <div class="custom_price_render"><span><?php echo __("Totaalprijs samengestelde product"); ?></span><span class="c_prijs"><?php echo $block->getProductPrice($_product); ?></span></div> -->
<?php 
   
//if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control qty-group">
              <span class="qty-button qty-minus">-</span>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
              <span class="qty-button qty-plus">+</span>
            </div>
        </div>
        <?php endif; ?>
        <!-- <div class="offer-button"><?php echo __("Offerte-aanvragen"); ?></div> -->
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?php echo "In winkelwagen/offerteaanvraag"//$block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        $(document).ready(function() {
            $(document).on('click', '.control.qty-group .qty-minus', function(){
                var qty_field = $(this).siblings('input.qty'),
                    current_qty_value = +qty_field.val();
                if(current_qty_value > 1){
                    qty_field.val(--current_qty_value);
                }
            });
            $(document).on('click', '.control.qty-group .qty-plus', function(){
                var qty_field = $(this).siblings('input.qty'),
                    current_qty_value = +qty_field.val();
                qty_field.val(++current_qty_value);
            });
        });
    });
</script>
<?php //endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
