<?php
$customerSession = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Customer\Model\Session::class);
?>
<div class="account-dd <?php if ($customerSession->isLoggedIn()){echo "loggedin";}?>">
	<?php
		if ($customerSession->isLoggedIn()) {
		   ?>
		   	<a href="<?= $block->getUrl('wishlist') ?>" class="wishlist-link">	<img
				    src="<?= $block->getViewFileUrl('images/wishlist-icon.png'); ?>"
				    alt="Wishlist"
				    width="24"
				    height="24"
				/> </a>
		   <?php
		} 
	?>
	

	<div class="account-ddown mv-account" id="mv-redirect"></div>
	</div>
</div>
<script>
    require(['jquery'], function ($) {
        $('ul.header.links').insertAfter('.mv-account');
        $("#mv-redirect").click(function(){
			$("ul.header.links").toggleClass("active");
		});
		$('.custom_menu').on('click', function () {
			$(".hamburg_menu").toggleClass('active');
			$(this).toggleClass("show");
			$('body').toggleClass("show");
		});
    });
    require([ "jquery" ], function($){
		$(window).scroll(function () {
		    if( $(window).scrollTop() > $('.page-wrapper').offset().top && !($('.page-wrapper').hasClass('sticky'))){
		    	$('.page-wrapper').addClass('sticky');
		    } else if ($(window).scrollTop() == 0){
		    	$('.page-wrapper').removeClass('sticky');
		    }
		});
	});
</script>

<style type="text/css">
	.customer-account-index .box.box-newsletter {
	    display: none;
	}
</style>
