<?php 
$helper = $this->helper('Emizen\Customsearch\Helper\Data');
$checkLogin = $helper->getCustomLogin(); 
?>
<?php if ($checkLogin) : ?>
    <?php
        $product = $block->getProduct();
        $descriptionData = $product->getData('description_huilijn');
        if ($descriptionData) {
             echo $descriptionData;
        }else{
            echo "Binnenkort beschikbaar";
        } 
        
    ?>
<?php endif; ?>
