<div id="custom-accordion" data-mage-init='{"accordion": { "openedState": "active", "collapsible": true, "active": "false", "multipleCollapsible": false }}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Werken</span>
        </div>
        <div data-role="content">
            <!-- Content for Section 1 -->
            <div id="nested-accordion" data-mage-init='{"accordion": { "openedState": "active", "collapsible": true, "active": "false", "multipleCollapsible": false }}'>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Basic</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-405"><a href="#">Basic bureaus</a></li>
                           <li class="prodcut-401"><a href="#">Basic aanbouwtafels</a></li>
                           <li class="prodcut-403"><a href="#">Basic bijzettafels</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Carré</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-419"><a href="#">Carré bureaus</a></li>
                           <li class="prodcut-417"><a href="#">Carré aanbouwtafels</a></li>
                           <li class="prodcut-418"><a href="#">Carré bijzettafels</a></li>
                        </ul>
                    </div>
                </div>
                <!-- Add more nested sections as needed -->
            </div>
        </div>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Akoestiek</span>
        </div>
        <div data-role="content">
            <!-- Content for Section 1 -->
            <div id="nested-accordion" data-mage-init='{"accordion": { "openedState": "active", "collapsible": true, "active": "false", "multipleCollapsible": false }}'>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Opbouw</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-357"><a href="#">Bench</a></li>
                           <li class="prodcut-454"><a href="#">Bladklem A</a></li>
                           <li class="prodcut-455"><a href="#">Bladklem B</a></li>
                           <li class="prodcut-456"><a href="#">Bladklem C</a></li>
                           <li class="prodcut-457"><a href="#">Frame adapters</a></li>
                           <li class="prodcut-458"><a href="#">Hoge voeten</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Vrijstaand</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-482"><a href="#">Vrijstaande panelen</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Ombouw</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-465"><a href="?product_id=465&amp;product_name=L-opstellingen">L-opstellingen</a></li>
                           <li class="prodcut-467"><a href="?product_id=467&amp;product_name=U-opstellingen">U-opstellingen</a></li>
                           <li class="prodcut-469"><a href="?product_id=469&amp;product_name=Z-opstellingen">Z-opstellingen</a></li>
                           <li class="prodcut-466"><a href="?product_id=466&amp;product_name=T-opstellingen">T-opstellingen</a></li>
                           <li class="prodcut-464"><a href="?product_id=464&amp;product_name=H-opstellingen">H-opstellingen</a></li>
                           <li class="prodcut-468"><a href="?product_id=468&amp;product_name=X-opstellingen">X-opstellingen</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Ombouw incl. bureaublad</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-478"><a href="?product_id=478&amp;product_name=U-Opstellingen">U-Opstellingen</a></li>
                           <li class="prodcut-477"><a href="?product_id=477&amp;product_name=H-Opstellingen">H-Opstellingen</a></li>
                           <li class="prodcut-476"><a href="?product_id=476&amp;product_name=Concentratie unit">Concentratie unit</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Vergaderen</span>
        </div>
        <div data-role="content">
            <!-- Content for Section 1 -->
            <div id="nested-accordion" data-mage-init='{"accordion": { "openedState": "active", "collapsible": true, "active": "false", "multipleCollapsible": false }}'>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Move</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-4007"><a href="?product_id=4007&amp;product_name=Move">Move</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Basic</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-518"><a href="?product_id=518&amp;product_name=Vergadertafels">Vergadertafels</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Carré</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-526"><a href="?product_id=526&amp;product_name=Vergadertafels">Vergadertafels</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Bridge</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                            <li class="prodcut-521"><a href="?product_id=521&amp;product_name=Vergadertafels">Vergadertafels</a></li>
                           <li class="prodcut-522"><a href="?product_id=522&amp;product_name=Vergadertafels massief hout">Vergadertafels massief hout</a></li>
                           <li class="prodcut-3298"><a href="?product_id=3298&amp;product_name=Bridge hoge tafels 90CM">Bridge hoge tafels 90CM</a></li>
                           <li class="prodcut-520"><a href="?product_id=520&amp;product_name=Bridge hoge tafels 110CM">Bridge hoge tafels 110CM</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Corner</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                            <li class="prodcut-528"><a href="?product_id=528&amp;product_name=Corner bijzettafels">Corner bijzettafels</a></li>
                           <li class="prodcut-530"><a href="?product_id=530&amp;product_name=Corner Vergadertafels">Corner Vergadertafels</a></li>
                           <li class="prodcut-529"><a href="?product_id=529&amp;product_name=Corner hoge tafels">Corner hoge tafels</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Kolom</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-536"><a href="?product_id=536&amp;product_name=Kolom vergadertafels">Kolom vergadertafels</a></li>
                            <li class="prodcut-510"><a href="?product_id=510&amp;product_name=Kolom hoge tafels">Kolom hoge tafels</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Lounge- en bijzettafels</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-528"><a href="?product_id=528&amp;product_name=Corner bijzettafels">Corner bijzettafels</a></li>
                           <li class="prodcut-542"><a href="?product_id=542&amp;product_name=Pipe">Pipe</a></li>
                           <li class="prodcut-541"><a href="?product_id=541&amp;product_name=Frame">Frame</a></li>
                           <li class="prodcut-538"><a href="?product_id=538&amp;product_name=Alfa Lounge">Alfa Lounge</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Bartafels</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-529"><a href="?product_id=529&amp;product_name=Corner hoge tafels">Corner hoge tafels</a></li>
                           <li class="prodcut-510"><a href="?product_id=510&amp;product_name=Kolom hoge tafels">Kolom hoge tafels</a></li>
                           <li class="prodcut-3298"><a href="?product_id=3298&amp;product_name=Bridge hoge tafels 90CM">Bridge hoge tafels 90CM</a></li>
                           <li class="prodcut-520"><a href="?product_id=520&amp;product_name=Bridge hoge tafels 110CM">Bridge hoge tafels 110CM</a></li>
                           <li class="prodcut-4007"><a href="?product_id=4007&amp;product_name=Move">Move</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Flexwall</span>
        </div>
        <div data-role="content">
            <!-- Content for Section 1 -->
            <div id="nested-accordion" data-mage-init='{"accordion": { "openedState": "active", "collapsible": true, "active": "false", "multipleCollapsible": false }}'>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Frames</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-4445"><a href="?product_id=4445&amp;product_name=Flexwall DWG bestanden">Flexwall DWG bestanden</a></li>
                           <li class="prodcut-3938"><a href="?product_id=3938&amp;product_name=Flexwall hoekblad">Flexwall hoekblad</a></li>
                           <li class="prodcut-3669"><a href="?product_id=3669&amp;product_name=Flexwall 40 cm">Flexwall 40 cm</a></li>
                           <li class="prodcut-2972"><a href="?product_id=2972&amp;product_name=Flexwall 80 cm">Flexwall 80 cm</a></li>
                           <li class="prodcut-3132"><a href="?product_id=3132&amp;product_name=Flexwall 119 cm">Flexwall 119 cm</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Opbergelementen</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-3106"><a href="?product_id=3106&amp;product_name=Flexwall opbergelementen">Flexwall opbergelementen</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Zitten</span>
                    </div>
                    <div data-role="content">
                        <ul id="sub_parent">
                           <li class="prodcut-3088"><a href="?product_id=3088&amp;product_name=Flexwall zitelement">Flexwall zitelement</a></li>
                            <li class="prodcut-591"><a href="?product_id=591&amp;product_name=Flexwall poefen">Flexwall poefen</a></li>
                        </ul>
                    </div>
                </div>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span>Panelen</span>
                    </div>
                    <div data-role="content">
                         <ul id="sub_parent">
                           <li class="prodcut-3701"><a href="?product_id=3701&amp;product_name=Flexwall panelen">Flexwall panelen</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>