<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Product Attachments Base for Magento 2
 */
/** @var \Magento\Framework\View\Element\Template $block */
$files = $block->getFiles();
?>
<?php foreach ($files as $file): ?>
    <?= /* @noEscape */ $block->getLayout()->getBlock($block->getParentName())->getRenderer()->getFileItemHtml($file) ?>
<?php endforeach; ?>
