<div class="custom-filter-sidebar">
    <ul id="custom-filters">
        <li class="prijslijsten_active"><a href="#" data-filter="prijslijsten">Prijslijsten</a></li>
        <li class="prijslijsten_active"><a href="#" data-filter="materialen">Materialen</a></li>
        <li class="prijslijsten_active"><a href="#" data-filter="dwg">DWG Bestanden</a></li>
        <!-- <li><a href="#" data-filter="afbeeldingen" data-cat="62">Afbeeldingen</a></li>
        <li><a href="#" data-filter="nieuwsbrieven">Nieuwsbrieven</a></li>
        <li><a href="#" data-filter="marketingpakketten">Marketing Pakketten</a></li> -->
    </ul>
</div>

<div id="filter-result"></div>
