<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>

<div class="block block-new-customer">
	<div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="3">Nog geen account?</strong>
    </div>
    <p><?php echo __("Are you a new customer and would you like to create an account?") ?></p>
    <p><?php echo __("Please contact us via E") ?>
        <a href="mailto:info@huislijnkantoormeubelen.nl">info@huislijnkantoormeubelen.nl</a>
    </p>
</div>


