<h2>Downloads </h2><br>

<?php
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('newsletter-image')
->toHtml();
?>


<br>
<iframe src="about:blank" id="adFrame" style="border: none; width: 100%; height: 700px;"></iframe>

<script>
require(['jquery'], function ($) {
    const iframe = document.getElementById('adFrame');
    const doc = iframe.contentWindow.document;

    doc.open();

    doc.write(`
        <html>
        <head>
            <style>
                .campaign {
                    padding: 10px 0 !important;
                }
                .campaign a {
				    color: #6e1f26;
				}
            </style>
        </head>
        <body>
            <script src="https://huislijnkantoormeubelen.us9.list-manage.com/generate-js/?u=9a82be5c326dd5f4103f75d9a&show=50&fid=29277"><\/script>
        </body>
        </html>
    `);

    doc.close();
});
</script>