<h2>Downloads </h2><br>
<iframe src="about:blank" id="adFrame" style="border: none; width: 100%; height: 250px;"></iframe>

<script>
  	require(['jquery'], function ($) {
	  const iframe = document.getElementById('adFrame');
	  const doc = iframe.contentWindow.document;
	  doc.open();
	  doc.write('<script src="https://huislijnkantoormeubelen.us9.list-manage.com/generate-js/?u=9a82be5c326dd5f4103f75d9a&show=10&fid=29277"><\/script>');
	  doc.close();
    });
</script>
